# Generated by Django 5.2.4 on 2026-01-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_remove_channel_owner_alter_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="server",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="API.server",
            ),
        ),
    ]
